### ISSUE TITLE
Add 'esdl:Buildings' parser

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etm-esdl#81]
For the Micro case a building parser has to be added in order to read the ESDL file (see \Projects/Active/537 Multi Modelling voor Integrale Besluitvorming (RVO)/03 Project/ESDL/Micro/EPS - Tholen Welgelegen (5)) provided by TNO.

**Comment by redekok** [comment]
@Charlottevm: as for the SBI sector filter, I would prefer the sector codes (e.g. "B06420") to be referred to in the Building assets instead of the uuid's. Since these SBI codes are unique as well, this couldn't hurt and makes the ESDL more transparent (and easier to parse for us). Could you discuss with the creators of the MMvIB micro case ESDL whether that would be possible?
